### ISSUE TITLE
dark-mode page transition issue

### ISSUE THREAD

**Issue by allan9595** [sharadcodes/geekyll-starter-blog#2]
Hi, I notice every time whenever I go to a different page in the dark mode or just first land at your demo page, the background will pause on light mode first, then turns into the dark mode. Would you be able to fix the issue so the transition will be more smooth and I won't see the light mode in the first place? Thanks

**Comment by sharadcodes** [comment]
> Hi, I notice every time whenever I go to a different page in the dark mode or just first land at your demo page, the background will pause on light mode first, then turns into the dark mode. Would you be able to fix the issue so the transition will be more smooth and I won't see the light mode in the first place? Thanks

Hey @allan9595, Yeah sure, I'll resolve issue

**Comment by sharadcodes** [comment]
> Hi, I notice every time whenever I go to a different page in the dark mode or just first land at your demo page, the background will pause on light mode first, then turns into the dark mode. Would you be able to fix the issue so the transition will be more smooth and I won't see the light mode in the first place? Thanks

Can you check it now ?
